<a href="https://colab.research.google.com/github/lindasheila/Python-Data-Cleaning-Analysis-of-NYC-Bus-Breakdowns/blob/main/SubCopy_of_%5BGuiding_Notebook%5D_AfterWork_Data_Science_Data_Cleaning_with_Python_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Guiding Notebook] Data Cleaning with Python Project

## 1. Defining the Question

### a) Specifying the Data Analysis Question

Specify the reasearch question that you'll be answering.

> i.e. Which was the most improved country year 2017 - 2018 as per the GDP ranking?

### b) Defining the Metric for Success

How will you know that your solution will have satisfied your research question?

### c) Understanding the context

Provide some background information....

### d) Recording the Experimental Design

Describe the steps/approach that you will use to answer the given question.

### e) Data Relevance

How relevant was the provided data?

## 2. Reading the Data

In [ ]:
# Importing our libraries
# ---
#
import pandas as pd

In [ ]:
# Load the data below
# ---
# Dataset url = https://bit.ly/BusBreakdownDataset
# ---
#
data= pd.read_csv('https://bit.ly/BusBreakdownDataset')

In [ ]:
# Checking the last 5 rows of data
# ---
data.head(5)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,NaN,11,Yes,No,Yes,11/05/2015 08:12:00 AM,NaN,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20MNS,2,Yes,Yes,No,11/05/2015 08:12:00 AM,NaN,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15MIN,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,NaN,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15 MIN,6,No,No,No,11/05/2015 08:14:00 AM,NaN,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,NaN,6,No,No,No,11/05/2015 08:14:00 AM,NaN,11/05/2015 08:14:08 AM,Running Late,School-Age

In [ ]:
# Sample 10 rows of data
# ---
#
data.sample(10)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
266943,2018-2019,1479583,Special Ed AM Run,2029,M842,Mechanical Problem,"02606,02735,02814",11/01/2018 06:05:00 AM,11/01/2018 06:30:00 AM,Manhattan,...,46-60 Min,0,Yes,Yes,No,11/01/2018 06:30:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
17690,2015-2016,1254426,General Ed AM Run,26665,K2165,Other,21861,03/08/2016 06:55:00 AM,03/08/2016 07:01:00 AM,Brooklyn,...,15 mins,0,Yes,No,No,03/08/2016 07:01:00 AM,NaN,03/08/2016 07:01:33 AM,Running Late,School-Age
145133,2018-2019,1488479,Special Ed PM Run,633,K229,Heavy Traffic,"22206,22222,22278",11/21/2018 02:20:00 PM,11/21/2018 02:25:00 PM,Brooklyn,...,31-45 Min,0,No,No,No,11/21/2018 02:25:00 PM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
150360,2017-2018,1369650,Special Ed AM Run,2631,L635,Heavy Traffic,"14450,14467",09/25/2017 07:25:00 AM,09/25/2017 07:26:00 AM,NaN,...,46-60 Min,1,Yes,Yes,Yes,09/25/2017 07:26:00 AM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
24899,2015-2016,1263027,General Ed AM Run,26627,K2126,Mechanical Problem,21009,04/18/2016 06:15:00 AM,04/18/2016 06:26:00 AM,Brooklyn,...,25min,0,Yes,Yes,No,04/18/2016 06:26:00 AM,NaN,04/18/2016 06:26:17 AM,Running Late,School-Age
226462,2018-2019,1465655,Special Ed PM Run,1426,M922,Heavy Traffic,"03279,03481,03491,03618",09/28/2018 12:00:00 PM,09/28/2018 12:01:00 PM,Manhattan,...,31-45 Min,0,Yes,No,No,09/28/2018 12:01:00 PM,NaN,01/01/1900 12:00:00 AM,Running Late,School-Age
112151,2015-2016,1226997,Special Ed AM Run,44279,K918,Other,19466,11/04/2015 06:30:00 AM,11/04/2015 06:39:00 AM,Brooklyn,...,30,0,Yes,Yes,No,11/04/2015 06:39:00 AM,NaN,11/04/2015 06:39:34 AM,Running Late,School-Age
275638,2016-2017,1306539,Special Ed PM Run,4528,K575,Delayed by School,22001,12/08/2016 02:55:00 PM,12/08/2016 02:57:00 PM,Brooklyn,...,20 MIN,0,Yes,Yes,Yes,12/08/2016 02:57:00 PM,NaN,12/08/2016 02:57:17 PM,Running Late,School-Age
160499,2015-2016,1220011,Special Ed AM Run,NI4478,K035,Heavy Traffic,21348,10/07/2015 08:15:00 AM,10/07/2015 08:24:00 AM,Brooklyn,...,30MIN,18,Yes,Yes,No,10/07/2015 08:24:00 AM,NaN,10/07/2015 08:24:08 AM,Running Late,School-Age
90423,2016-2017,1340724,Special Ed AM Run,4123,K114,Won`t Start,16409,04/21/2017 06:13:00 AM,04/21/2017 06:13:00 AM,Brooklyn,...,20 mins,0,Yes,Yes,No,04/21/2017 06:13:00 AM,NaN,04/21/2017 08:53:40 AM,Running Late,School-Age

In [ ]:
# Checking number of rows and columns
# ---
#
data.size
data.shape
print('The number of raw is', data.shape[0],'The number of column is',  data.shape[1])

The number of raw is 281110 The number of column is 21

In [ ]:
# Checking datatypes
# ---
#
data.dtypes

School_Year                        object
Busbreakdown_ID                     int64
Run_Type                           object
Bus_No                             object
Route_Number                       object
Reason                             object
Schools_Serviced                   object
Occurred_On                        object
Created_On                         object
Boro                               object
Bus_Company_Name                   object
How_Long_Delayed                   object
Number_Of_Students_On_The_Bus       int64
Has_Contractor_Notified_Schools    object
Has_Contractor_Notified_Parents    object
Have_You_Alerted_OPT               object
Informed_On                        object
Incident_Number                    object
Last_Updated_On                    object
Breakdown_or_Running_Late          object
School_Age_or_PreK                 object
dtype: object

Record your observations below:

*   Observation 1
*   Observation 2

## 3. External Data Source Validation

You can make sure your data matches other credible information. This ensures that the measurements are roughly in line with what they should be and it serves as a check on what other things might be wrong in your dataset.

External validation can often be as simple as checking your data against some other data i.e. country population your dataset with country population on world bank data.

Replace the text found on this text cell with your external data source validation information.

## 4. Data Preparation

### Performing Data Cleaning

In [ ]:
# Checking datatypes and missing entries of all the variables
# ---
#
print('Column''s name are',data.columns)
print()
print('Total Raw for each column', data.isnull().count()) # total raw for each column
print()
print('Count missing values', data.isnull().sum())

Columns name are Index(['School_Year', 'Busbreakdown_ID', 'Run_Type', 'Bus_No', 'Route_Number',
       'Reason', 'Schools_Serviced', 'Occurred_On', 'Created_On', 'Boro',
       'Bus_Company_Name', 'How_Long_Delayed', 'Number_Of_Students_On_The_Bus',
       'Has_Contractor_Notified_Schools', 'Has_Contractor_Notified_Parents',
       'Have_You_Alerted_OPT', 'Informed_On', 'Incident_Number',
       'Last_Updated_On', 'Breakdown_or_Running_Late', 'School_Age_or_PreK'],
      dtype='object')

Total Raw for each column School_Year                        281110
Busbreakdown_ID                    281110
Run_Type                           281110
Bus_No                             281110
Route_Number                       281110
Reason                             281110
Schools_Serviced                   281110
Occurred_On                        281110
Created_On                         281110
Boro                               281110
Bus_Company_Name                   281110
How_Long_Delayed                   281110
Number_Of_Students_On_The_Bus      281110
Has_Contractor_Notified_Schools    281110
Has_Contractor_Notified_Parents    281110
Have_You_Alerted_OPT               281110
Informed_On                        281110
Incident_Number                    281110
Last_Updated_On                    281110
Breakdown_or_Running_Late          281110
School_Age_or_PreK                 281110
dtype: int64

Count missing values School_Year                             0
Busbreakdown_ID                         0
Run_Type                                3
Bus_No                                  9
Route_Number                            7
Reason                                  2
Schools_Serviced                        7
Occurred_On                             0
Created_On                              0
Boro                                13461
Bus_Company_Name                        0
How_Long_Delayed                    35608
Number_Of_Students_On_The_Bus           0
Has_Contractor_Notified_Schools         0
Has_Contractor_Notified_Parents         0
Have_You_Alerted_OPT                    0
Informed_On                             0
Incident_Number                    271627
Last_Updated_On                         0
Breakdown_or_Running_Late               0
School_Age_or_PreK                      0
dtype: int64

In [ ]:
#convert type
data[['Busbreakdown_ID','Number_Of_Students_On_The_Bus']] = data[['Busbreakdown_ID','Number_Of_Students_On_The_Bus']].astype(int)

#printing record for better view
data[['School_Age_or_PreK','Breakdown_or_Running_Late','Last_Updated_On','Incident_Number', 'Informed_On','Have_You_Alerted_OPT', 'Boro','Bus_Company_Name']]

,School_Age_or_PreK,Breakdown_or_Running_Late,Last_Updated_On,Incident_Number,Informed_On,Have_You_Alerted_OPT,Boro,Bus_Company_Name
0,School-Age,Running Late,11/05/2015 08:12:14 AM,NaN,11/05/2015 08:12:00 AM,Yes,New Jersey,"RELIANT TRANS, INC. (B232"
1,School-Age,Running Late,11/05/2015 08:13:34 AM,NaN,11/05/2015 08:12:00 AM,No,Manhattan,HOYT TRANSPORTATION CORP.
2,Pre-K,Running Late,11/05/2015 08:13:22 AM,NaN,11/05/2015 08:13:00 AM,Yes,Bronx,"G.V.C., LTD."
3,School-Age,Running Late,11/05/2015 08:14:04 AM,NaN,11/05/2015 08:14:00 AM,No,Manhattan,"RELIANT TRANS, INC. (B232"
4,School-Age,Running Late,11/05/2015 08:14:08 AM,NaN,11/05/2015 08:14:00 AM,No,Manhattan,"RELIANT TRANS, INC. (B232"
...,...,...,...,...,...,...,...,...
281105,Pre-K,Running Late,04/05/2017 08:10:15 AM,NaN,04/05/2017 08:10:00 AM,No,Bronx,"G.V.C., LTD."
281106,Pre-K,Running Late,04/24/2017 07:44:15 AM,NaN,04/24/2017 07:44:00 AM,No,Bronx,"G.V.C., LTD."
281107,School-Age,Running Late,05/25/2017 04:34:36 PM,90323827,05/25/2017 04:28:00 PM,Yes,Bronx,G.V.C. LTD. (B2192)
281108,School-Age,Breakdown,05/25/2017 04:30:07 PM,NaN,05/25/2017 04:30:00 PM,No,Queens,LITTLE RICHIE BUS SERVICE
281109,School-Age,Running Late,05/25/2017 04:37:37 PM,NaN,05/25/2017 04:37:00 PM,Yes,Brooklyn,"RELIANT TRANS, INC. (B232"

In [ ]:
data

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,NaN,11,Yes,No,Yes,11/05/2015 08:12:00 AM,NaN,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20MNS,2,Yes,Yes,No,11/05/2015 08:12:00 AM,NaN,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15MIN,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,NaN,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15 MIN,6,No,No,No,11/05/2015 08:14:00 AM,NaN,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,NaN,6,No,No,No,11/05/2015 08:14:00 AM,NaN,11/05/2015 08:14:08 AM,Running Late,School-Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281105,2016-2017,1338452,Pre-K/EI,9345,2,Heavy Traffic,C530,04/05/2017 08:00:00 AM,04/05/2017 08:10:00 AM,Bronx,...,15-20,7,Yes,Yes,No,04/05/2017 08:10:00 AM,NaN,04/05/2017 08:10:15 AM,Running Late,Pre-K
281106,2016-2017,1341521,Pre-K/EI,0001,5,Heavy Traffic,C579,04/24/2017 07:42:00 AM,04/24/2017 07:44:00 AM,Bronx,...,20 MINS,0,Yes,Yes,No,04/24/2017 07:44:00 AM,NaN,04/24/2017 07:44:15 AM,Running Late,Pre-K
281107,2016-2017,1353044,Special Ed PM Run,GC0112,X928,Heavy Traffic,09003,05/25/2017 04:22:00 PM,05/25/2017 04:28:00 PM,Bronx,...,20-25MINS,0,Yes,Yes,Yes,05/25/2017 04:28:00 PM,90323827,05/25/2017 04:34:36 PM,Running Late,School-Age
281108,2016-2017,1353045,Special Ed PM Run,5525D,Q920,Won`t Start,24457,05/25/2017 04:27:00 PM,05/25/2017 04:30:00 PM,Queens,...,NaN,0,Yes,Yes,No,05/25/2017 04:30:00 PM,NaN,05/25/2017 04:30:07 PM,Breakdown,School-Age
281109,2016-2017,1353046,Project Read PM Run,2530,K617,Other,21436,05/25/2017 04:36:00 PM,05/25/2017 04:37:00 PM,Brooklyn,...,45min,7,Yes,Yes,Yes,05/25/2017 04:37:00 PM,NaN,05/25/2017 04:37:37 PM,Running Late,School-Age

In [ ]:
# changing Min
data['How_Long_Delayed']=data['How_Long_Delayed'].str.replace('MNS','MIN')
data['How_Long_Delayed']=data['How_Long_Delayed'].str.replace('MINS','MIN')
data['How_Long_Delayed']=data['How_Long_Delayed'].str.replace('min','MIN')
data['How_Long_Delayed']=data['How_Long_Delayed'].str.replace('mikn','MIN')
data['How_Long_Delayed']=data['How_Long_Delayed'].str.replace('MINIUTE','MIN')
data['How_Long_Delayed'] = data['How_Long_Delayed'].str.replace(r'\s*MIN\s*', '', regex=True)
data['How_Long_Delayed'] = data['How_Long_Delayed'].str.replace(' MIN MIN', '', regex=False)
data['How_Long_Delayed'] = data['How_Long_Delayed'].str.replace('  mns', '', regex=False)
data['How_Long_Delayed'] = data['How_Long_Delayed'].str.replace('mn', '', regex=False)


# remove MIN
#data['How_Long_Delayed'] = data['How_Long_Delayed'].str.replace(' MIN$', '', regex=True)
data['How_Long_Delayed'] = data['How_Long_Delayed'].str.strip().str.replace(r'\s*MIN$', '', regex=True)

#data
#add MIN without space uniformly
data['How_Long_Delayed'] = data['How_Long_Delayed'].astype(str) + ' MIN'
#data

# replace nan by 0

data['How_Long_Delayed']=data['How_Long_Delayed'].str.replace('nan','0')
# replacing the missing value

data['Incident_Number'] = data['Incident_Number'].fillna(0)
print(data)

#unique_values = data_no_duplicates['How_Long_Delayed'].unique()
#print(unique_values)

       School_Year  Busbreakdown_ID             Run_Type  Bus_No Route_Number  \
0        2015-2016          1227538    Special Ed AM Run    2621         J711
1        2015-2016          1227539    Special Ed AM Run    1260         M351
2        2015-2016          1227540             Pre-K/EI     418            3
3        2015-2016          1227541    Special Ed AM Run    4522         M271
4        2015-2016          1227542    Special Ed AM Run    3124         M373
...            ...              ...                  ...     ...          ...
281105   2016-2017          1338452             Pre-K/EI    9345            2
281106   2016-2017          1341521             Pre-K/EI    0001            5
281107   2016-2017          1353044    Special Ed PM Run  GC0112         X928
281108   2016-2017          1353045    Special Ed PM Run   5525D         Q920
281109   2016-2017          1353046  Project Read PM Run    2530         K617

               Reason Schools_Serviced             Occurred_On  \
0       Heavy Traffic            75003  11/05/2015 08:10:00 AM
1       Heavy Traffic            06716  11/05/2015 08:10:00 AM
2       Heavy Traffic             C445  11/05/2015 08:09:00 AM
3       Heavy Traffic            02699  11/05/2015 08:12:00 AM
4       Heavy Traffic            02116  11/05/2015 08:13:00 AM
...               ...              ...                     ...
281105  Heavy Traffic             C530  04/05/2017 08:00:00 AM
281106  Heavy Traffic             C579  04/24/2017 07:42:00 AM
281107  Heavy Traffic            09003  05/25/2017 04:22:00 PM
281108    Won`t Start            24457  05/25/2017 04:27:00 PM
281109          Other            21436  05/25/2017 04:36:00 PM

                    Created_On        Boro  ... How_Long_Delayed  \
0       11/05/2015 08:12:00 AM  New Jersey  ...            0 MIN
1       11/05/2015 08:12:00 AM   Manhattan  ...           20 MIN
2       11/05/2015 08:13:00 AM       Bronx  ...           15 MIN
3       11/05/2015 08:14:00 AM   Manhattan  ...           15 MIN
4       11/05/2015 08:14:00 AM   Manhattan  ...            0 MIN
...                        ...         ...  ...              ...
281105  04/05/2017 08:10:00 AM       Bronx  ...        15-20 MIN
281106  04/24/2017 07:44:00 AM       Bronx  ...           20 MIN
281107  05/25/2017 04:28:00 PM       Bronx  ...        20-25 MIN
281108  05/25/2017 04:30:00 PM      Queens  ...            0 MIN
281109  05/25/2017 04:37:00 PM    Brooklyn  ...           45 MIN

       Number_Of_Students_On_The_Bus  Has_Contractor_Notified_Schools  \
0                                 11                              Yes
1                                  2                              Yes
2                                  8                              Yes
3                                  6                               No
4                                  6                               No
...                              ...                              ...
281105                             7                              Yes
281106                             0                              Yes
281107                             0                              Yes
281108                             0                              Yes
281109                             7                              Yes

       Has_Contractor_Notified_Parents Have_You_Alerted_OPT  \
0                                   No                  Yes
1                                  Yes                   No
2                                  Yes                  Yes
3                                   No                   No
4                                   No                   No
...                                ...                  ...
281105                             Yes                   No
281106                             Yes                   No
281107                             Yes                  Yes
281108                             Yes                   No
281109                             Yes                  Yes

                   Informed_On Incident_Number         Last_Updated_On  \
0       11/05/2015 08:12:00 AM               0  11/05/2015 08:12:14 AM
1       11/05/2015 08:12:00 AM               0  11/05/2015 08:13:34 AM
2       11/05/2015 08:13:00 AM               0  11/05/2015 08:13:22 AM
3       11/05/2015 08:14:00 AM               0  11/05/2015 08:14:04 AM
4       11/05/2015 08:14:00 AM               0  11/05/2015 08:14:08 AM
...                        ...             ...                     ...
281105  04/05/2017 08:10:00 AM               0  04/05/2017 08:10:15 AM
281106  04/24/2017 07:44:00 AM               0  04/24/2017 07:44:15 AM
281107  05/25/2017 04:28:00 PM        90323827  05/25/2017 04:34:36 PM
281108  05/25/2017 04:30:00 PM               0  05/25/2017 04:30:07 PM
281109  05/25/2017 04:37:00 PM               0  05/25/2017 04:37:37 PM

       Breakdown_or_Running_Late School_Age_or_PreK
0                   Running Late         School-Age
1                   Running Late         School-Age
2                   Running Late              Pre-K
3                   Running Late         School-Age
4                   Running Late         School-Age
...                          ...                ...
281105              Running Late              Pre-K
281106              Running Late              Pre-K
281107              Running Late         School-Age
281108                 Breakdown         School-Age
281109              Running Late         School-Age

[281110 rows x 21 columns]

In [ ]:
data.dtypes

School_Year                        object
Busbreakdown_ID                     int64
Run_Type                           object
Bus_No                             object
Route_Number                       object
Reason                             object
Schools_Serviced                   object
Occurred_On                        object
Created_On                         object
Boro                               object
Bus_Company_Name                   object
How_Long_Delayed                   object
Number_Of_Students_On_The_Bus       int64
Has_Contractor_Notified_Schools    object
Has_Contractor_Notified_Parents    object
Have_You_Alerted_OPT               object
Informed_On                        object
Incident_Number                    object
Last_Updated_On                    object
Breakdown_or_Running_Late          object
School_Age_or_PreK                 object
dtype: object

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Standardizing your dataset i.e. variable renaming
# ---
#
#data.rename(columns={'Busbreakdown_ID': 'Bus_Breakdown_ID', 'Bus_No': 'Bus_Number'}, inplace=True)
#or
data.columns=['School_Year', 'Bus_Breakdown_ID', 'Run_Type', 'Bus_Number', 'Route_Number',
       'Reason', 'Schools_Serviced', 'Occurred_On', 'Created_On', 'Borough',
       'Bus_Company_Name', 'How_Long_Delayed', 'Number_Of_Students_On_The_Bus',
       'Has_Contractor_Notified_Schools', 'Has_Contractor_Notified_Parents',
       'Have_You_Alerted_OPT', 'Informed_On', 'Incident_Number',
       'Last_Updated_On', 'Breakdown_or_Running_Late', 'School_Age_or_PreK']

data

,School_Year,Bus_Breakdown_ID,Run_Type,Bus_Number,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Borough,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,0 MIN,11,Yes,No,Yes,11/05/2015 08:12:00 AM,0,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20 MIN,2,Yes,Yes,No,11/05/2015 08:12:00 AM,0,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15 MIN,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,0,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15 MIN,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,0 MIN,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:08 AM,Running Late,School-Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281105,2016-2017,1338452,Pre-K/EI,9345,2,Heavy Traffic,C530,04/05/2017 08:00:00 AM,04/05/2017 08:10:00 AM,Bronx,...,15-20 MIN,7,Yes,Yes,No,04/05/2017 08:10:00 AM,0,04/05/2017 08:10:15 AM,Running Late,Pre-K
281106,2016-2017,1341521,Pre-K/EI,0001,5,Heavy Traffic,C579,04/24/2017 07:42:00 AM,04/24/2017 07:44:00 AM,Bronx,...,20 MIN,0,Yes,Yes,No,04/24/2017 07:44:00 AM,0,04/24/2017 07:44:15 AM,Running Late,Pre-K
281107,2016-2017,1353044,Special Ed PM Run,GC0112,X928,Heavy Traffic,09003,05/25/2017 04:22:00 PM,05/25/2017 04:28:00 PM,Bronx,...,20-25 MIN,0,Yes,Yes,Yes,05/25/2017 04:28:00 PM,90323827,05/25/2017 04:34:36 PM,Running Late,School-Age
281108,2016-2017,1353045,Special Ed PM Run,5525D,Q920,Won`t Start,24457,05/25/2017 04:27:00 PM,05/25/2017 04:30:00 PM,Queens,...,0 MIN,0,Yes,Yes,No,05/25/2017 04:30:00 PM,0,05/25/2017 04:30:07 PM,Breakdown,School-Age
281109,2016-2017,1353046,Project Read PM Run,2530,K617,Other,21436,05/25/2017 04:36:00 PM,05/25/2017 04:37:00 PM,Brooklyn,...,45 MIN,7,Yes,Yes,Yes,05/25/2017 04:37:00 PM,0,05/25/2017 04:37:37 PM,Running Late,School-Age

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking how many duplicate rows are there in the data
# ---
#
print('The total number of duplocate is', data.duplicated().sum())
# to drop duplicate if any

data_no_duplicates = data.drop_duplicates()

# Display the dataset after removing duplicate rows
data_no_duplicates

The total number of duplocate is 0

,School_Year,Bus_Breakdown_ID,Run_Type,Bus_Number,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Borough,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,0 MIN,11,Yes,No,Yes,11/05/2015 08:12:00 AM,0,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20 MIN,2,Yes,Yes,No,11/05/2015 08:12:00 AM,0,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15 MIN,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,0,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15 MIN,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,0 MIN,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:08 AM,Running Late,School-Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281105,2016-2017,1338452,Pre-K/EI,9345,2,Heavy Traffic,C530,04/05/2017 08:00:00 AM,04/05/2017 08:10:00 AM,Bronx,...,15-20 MIN,7,Yes,Yes,No,04/05/2017 08:10:00 AM,0,04/05/2017 08:10:15 AM,Running Late,Pre-K
281106,2016-2017,1341521,Pre-K/EI,0001,5,Heavy Traffic,C579,04/24/2017 07:42:00 AM,04/24/2017 07:44:00 AM,Bronx,...,20 MIN,0,Yes,Yes,No,04/24/2017 07:44:00 AM,0,04/24/2017 07:44:15 AM,Running Late,Pre-K
281107,2016-2017,1353044,Special Ed PM Run,GC0112,X928,Heavy Traffic,09003,05/25/2017 04:22:00 PM,05/25/2017 04:28:00 PM,Bronx,...,20-25 MIN,0,Yes,Yes,Yes,05/25/2017 04:28:00 PM,90323827,05/25/2017 04:34:36 PM,Running Late,School-Age
281108,2016-2017,1353045,Special Ed PM Run,5525D,Q920,Won`t Start,24457,05/25/2017 04:27:00 PM,05/25/2017 04:30:00 PM,Queens,...,0 MIN,0,Yes,Yes,No,05/25/2017 04:30:00 PM,0,05/25/2017 04:30:07 PM,Breakdown,School-Age
281109,2016-2017,1353046,Project Read PM Run,2530,K617,Other,21436,05/25/2017 04:36:00 PM,05/25/2017 04:37:00 PM,Brooklyn,...,45 MIN,7,Yes,Yes,Yes,05/25/2017 04:37:00 PM,0,05/25/2017 04:37:37 PM,Running Late,School-Age

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking if any of the columns are all null
# ---
#

#data_no_duplicates.isnull().sum()
data_no_duplicates.isnull().all(axis=0)

School_Year                        False
Bus_Breakdown_ID                   False
Run_Type                           False
Bus_Number                         False
Route_Number                       False
Reason                             False
Schools_Serviced                   False
Occurred_On                        False
Created_On                         False
Borough                            False
Bus_Company_Name                   False
How_Long_Delayed                   False
Number_Of_Students_On_The_Bus      False
Has_Contractor_Notified_Schools    False
Has_Contractor_Notified_Parents    False
Have_You_Alerted_OPT               False
Informed_On                        False
Incident_Number                    False
Last_Updated_On                    False
Breakdown_or_Running_Late          False
School_Age_or_PreK                 False
dtype: bool

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking if any of the rows are all null
# ---
#

print(data_no_duplicates.isnull().all(axis=1).sum())
print()
print(data_no_duplicates.isnull().all(axis=1))

0

0         False
1         False
2         False
3         False
4         False
          ...
281105    False
281106    False
281107    False
281108    False
281109    False
Length: 281110, dtype: bool

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking if the "Yes/No" fields contain only these 2 values
# for have_you_alerted_opt variable
# ---
# Hint: Use unique() function
#
unique_values = data_no_duplicates['Have_You_Alerted_OPT'].unique()
print(unique_values)

['Yes' 'No']

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking if the "Yes/No" fields contain only these 2 values
# for has_contractor_notified_parents variable
# ---
#


unique_values = data_no_duplicates['Has_Contractor_Notified_Parents'].unique()
print(unique_values)

['No' 'Yes']

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking if the "Yes/No" fields contain only these 2 values
# for has_contractor_notified_schools variable
# ---
#
unique_values = data_no_duplicates['Has_Contractor_Notified_Schools'].unique()
print(unique_values)

['Yes' 'No']

We observe the following from our dataset:

*   Observation 1
*   Observation 2

In [ ]:
# Checking unique values in break_down_or_running_late variable to ensure there is no duplication
# ---
#
unique_values = data_no_duplicates['Breakdown_or_Running_Late'].unique()
print(unique_values)

['Running Late' 'Breakdown']

In [ ]:
data_no_duplicates.columns

Index(['School_Year', 'Bus_Breakdown_ID', 'Run_Type', 'Bus_Number',
       'Route_Number', 'Reason', 'Schools_Serviced', 'Occurred_On',
       'Created_On', 'Borough', 'Bus_Company_Name', 'How_Long_Delayed',
       'Number_Of_Students_On_The_Bus', 'Has_Contractor_Notified_Schools',
       'Has_Contractor_Notified_Parents', 'Have_You_Alerted_OPT',
       'Informed_On', 'Incident_Number', 'Last_Updated_On',
       'Breakdown_or_Running_Late', 'School_Age_or_PreK'],
      dtype='object')

In [ ]:
# Checking unique values in school_age_or_prek variable
# ---
#


unique_values = data_no_duplicates['School_Age_or_PreK'].unique()
print(unique_values)

['School-Age' 'Pre-K']

In [ ]:
# Checking unique values in school_year variable
# ---
#

unique_values = data_no_duplicates['School_Year'].unique()
print(unique_values)

['2015-2016' '2017-2018' '2018-2019' '2016-2017' '2019-2020']

In [ ]:
# Checking unique values in reason variable
# ---
#

unique_values = data_no_duplicates['Reason'].unique()
print(unique_values)

['Heavy Traffic' 'Flat Tire' 'Other' 'Won`t Start' 'Mechanical Problem'
 'Problem Run' 'Accident' 'Late return from Field Trip'
 'Delayed by School' 'Weather Conditions' nan]

In [ ]:
# Checking unique values in run_type variable
# ---
#

unique_values = data_no_duplicates['Run_Type'].unique()
print(unique_values)

['Special Ed AM Run' 'Pre-K/EI' 'General Ed AM Run'
 'General Ed Field Trip' 'Special Ed PM Run' 'General Ed PM Run'
 'Project Read PM Run' 'Special Ed Field Trip' 'Project Read AM Run'
 'Project Read Field Trip' nan]

In [ ]:
unique_values = data_no_duplicates['How_Long_Delayed'].unique()
print(unique_values)

['0 MIN' '20 MIN' '15 MIN' ... '154 MIN' '5 - 10 MIN' '40 -50 MIN']

In [ ]:
# Checking unique values in boro variable
# ---
#

unique_values = data_no_duplicates['Borough'].unique()
print(unique_values)

['New Jersey' 'Manhattan' 'Bronx' 'Westchester' 'Brooklyn'
 'Rockland County' 'Nassau County' nan 'Queens' 'Staten Island'
 'Connecticut' 'All Boroughs']

### Overall Data Cleaning Observations
**Missing Values**

- There are a large number of missing values in the fields "How_Long_Delayed" which is important to our analysis.
- There is an extremely large number of missing values in the "Incident_number" field but this is not incidental to our analysis and cannot be filled in without additional information.

**Error in values**

- "How_Long_Delayed" contains string values such as "MINS" or "mins" and a range of values, which needs to be changed to single integer value for our analysis.

**Error in Datatypes**

- "How_Long_Delayed" is a string datatype, should be converted to integer type.

**Error in field names**
- The column name "Boro" should be renamed to "Borough".

### Next Steps: Data Cleaning Steps

**Error in values**

- Extract the first integer value (lowest delay time) in the column "How_Long_Delayed"


**Missing Values**

- Impute the missing values in the field "How_Long_Delayed" with the mean value.


**Error in Datatypes**

- Convert "How_Long_Delayed" to int datatype.



**Error in field names**

- Rename the column "Boro" to "Borough".

In [ ]:
# Lets first start by creating a copy of our dataframe
# df_clean = df.copy(). We will use this copy as our cleaning copy.
# ---
#
df_clean = data_no_duplicates.copy()
df_clean.head()

,School_Year,Bus_Breakdown_ID,Run_Type,Bus_Number,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Borough,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,0 MIN,11,Yes,No,Yes,11/05/2015 08:12:00 AM,0,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20 MIN,2,Yes,Yes,No,11/05/2015 08:12:00 AM,0,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15 MIN,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,0,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15 MIN,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,0 MIN,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:08 AM,Running Late,School-Age

In [ ]:
# Then extracting the lowest delay time in the column how_long_delayed from the string
#

df_clean['How_Long_Delayed'] = df_clean['How_Long_Delayed'].str.extract('(\d+)')
df_clean['How_Long_Delayed'].head(281110)

#pd.reset_option('display.max_rows')

0          0
1         20
2         15
3         15
4          0
          ..
281105    15
281106    20
281107    20
281108     0
281109    45
Name: How_Long_Delayed, Length: 281110, dtype: object

We impute the null values in 'how_long_delayed' column with mean of the column. This will take a couple of steps...

In [ ]:
# We first convert our how_long_delayed to float type to allow for imputation
# ---
#

df_clean['How_Long_Delayed'] = df_clean['How_Long_Delayed'].str.extract('(\d+)').astype(float)

In [ ]:
# Then later perform our mean imputation
# ---
#
print('Check the type of the column How_Long_Delayed: ', df_clean['How_Long_Delayed'].dtype)
print(df_clean['How_Long_Delayed'])
# I would like to replace only the 0 MIN value by the MIN
mean_delay=df_clean['How_Long_Delayed'].mean()

print('The Mean is:', mean_delay)

#or
# one way maybe to proceed  is to  compute the mean without considering the 0 MIN value

#mean_delay = df_clean[df_clean['How_Long_Delayed'] != 0]['How_Long_Delayed'].mean()

df_clean['How_Long_Delayed'] = df_clean['How_Long_Delayed'].replace(0, mean_delay)


#df_clean['How_Long_Delayed']
df_clean['How_Long_Delayed']
# check the replacement
print('Number of empty entries in How Long Delayed:', df_clean.isnull().all(axis=1).sum())
print()
print()
print(df_clean['How_Long_Delayed'])
print()
print()
print('Print only raw where the replacement has been done', df_clean[df_clean['How_Long_Delayed'] == mean_delay]['How_Long_Delayed'])

Check the type of the column How_Long_Delayed:  float64
0          0.0
1         20.0
2         15.0
3         15.0
4          0.0
          ...
281105    15.0
281106    20.0
281107    20.0
281108     0.0
281109    45.0
Name: How_Long_Delayed, Length: 281110, dtype: float64
The Mean is: 24.5944656284523
Number of empty entries in How Long Delayed: 0


0         24.594466
1         20.000000
2         15.000000
3         15.000000
4         24.594466
            ...
281105    15.000000
281106    20.000000
281107    20.000000
281108    24.594466
281109    45.000000
Name: How_Long_Delayed, Length: 281110, dtype: float64


Print only raw where the replacement has been done 0         24.594466
4         24.594466
16        24.594466
18        24.594466
22        24.594466
            ...
281071    24.594466
281072    24.594466
281086    24.594466
281100    24.594466
281108    24.594466
Name: How_Long_Delayed, Length: 50244, dtype: float64

In [ ]:
# Then convert back our how_long_delayed column to integer datatype
# ---
#
# first print Not a Number(NaN) value
#print('Print the raw with NAN', df_clean[df_clean['How_Long_Delayed'].isna()].sum())
# Fill NaN values with the mean value
df_clean['How_Long_Delayed'] = df_clean['How_Long_Delayed'].fillna(mean_delay)
df_clean['How_Long_Delayed']=df_clean['How_Long_Delayed'].astype(int)

print(df_clean.dtypes)

print(df_clean)

School_Year                        object
Bus_Breakdown_ID                    int64
Run_Type                           object
Bus_Number                         object
Route_Number                       object
Reason                             object
Schools_Serviced                   object
Occurred_On                        object
Created_On                         object
Borough                            object
Bus_Company_Name                   object
How_Long_Delayed                    int64
Number_Of_Students_On_The_Bus       int64
Has_Contractor_Notified_Schools    object
Has_Contractor_Notified_Parents    object
Have_You_Alerted_OPT               object
Informed_On                        object
Incident_Number                    object
Last_Updated_On                    object
Breakdown_or_Running_Late          object
School_Age_or_PreK                 object
dtype: object
       School_Year  Bus_Breakdown_ID             Run_Type Bus_Number  \
0        2015-2016           1227538    Special Ed AM Run       2621
1        2015-2016           1227539    Special Ed AM Run       1260
2        2015-2016           1227540             Pre-K/EI        418
3        2015-2016           1227541    Special Ed AM Run       4522
4        2015-2016           1227542    Special Ed AM Run       3124
...            ...               ...                  ...        ...
281105   2016-2017           1338452             Pre-K/EI       9345
281106   2016-2017           1341521             Pre-K/EI       0001
281107   2016-2017           1353044    Special Ed PM Run     GC0112
281108   2016-2017           1353045    Special Ed PM Run      5525D
281109   2016-2017           1353046  Project Read PM Run       2530

       Route_Number         Reason Schools_Serviced             Occurred_On  \
0              J711  Heavy Traffic            75003  11/05/2015 08:10:00 AM
1              M351  Heavy Traffic            06716  11/05/2015 08:10:00 AM
2                 3  Heavy Traffic             C445  11/05/2015 08:09:00 AM
3              M271  Heavy Traffic            02699  11/05/2015 08:12:00 AM
4              M373  Heavy Traffic            02116  11/05/2015 08:13:00 AM
...             ...            ...              ...                     ...
281105            2  Heavy Traffic             C530  04/05/2017 08:00:00 AM
281106            5  Heavy Traffic             C579  04/24/2017 07:42:00 AM
281107         X928  Heavy Traffic            09003  05/25/2017 04:22:00 PM
281108         Q920    Won`t Start            24457  05/25/2017 04:27:00 PM
281109         K617          Other            21436  05/25/2017 04:36:00 PM

                    Created_On     Borough  ... How_Long_Delayed  \
0       11/05/2015 08:12:00 AM  New Jersey  ...               24
1       11/05/2015 08:12:00 AM   Manhattan  ...               20
2       11/05/2015 08:13:00 AM       Bronx  ...               15
3       11/05/2015 08:14:00 AM   Manhattan  ...               15
4       11/05/2015 08:14:00 AM   Manhattan  ...               24
...                        ...         ...  ...              ...
281105  04/05/2017 08:10:00 AM       Bronx  ...               15
281106  04/24/2017 07:44:00 AM       Bronx  ...               20
281107  05/25/2017 04:28:00 PM       Bronx  ...               20
281108  05/25/2017 04:30:00 PM      Queens  ...               24
281109  05/25/2017 04:37:00 PM    Brooklyn  ...               45

        Number_Of_Students_On_The_Bus  Has_Contractor_Notified_Schools  \
0                                  11                              Yes
1                                   2                              Yes
2                                   8                              Yes
3                                   6                               No
4                                   6                               No
...                               ...                              ...
281105                              7                              Yes
281106                              0                              Yes
281107                              0                              Yes
281108                              0                              Yes
281109                              7                              Yes

       Has_Contractor_Notified_Parents Have_You_Alerted_OPT  \
0                                   No                  Yes
1                                  Yes                   No
2                                  Yes                  Yes
3                                   No                   No
4                                   No                   No
...                                ...                  ...
281105                             Yes                   No
281106                             Yes                   No
281107                             Yes                  Yes
281108                             Yes                   No
281109                             Yes                  Yes

                   Informed_On Incident_Number         Last_Updated_On  \
0       11/05/2015 08:12:00 AM               0  11/05/2015 08:12:14 AM
1       11/05/2015 08:12:00 AM               0  11/05/2015 08:13:34 AM
2       11/05/2015 08:13:00 AM               0  11/05/2015 08:13:22 AM
3       11/05/2015 08:14:00 AM               0  11/05/2015 08:14:04 AM
4       11/05/2015 08:14:00 AM               0  11/05/2015 08:14:08 AM
...                        ...             ...                     ...
281105  04/05/2017 08:10:00 AM               0  04/05/2017 08:10:15 AM
281106  04/24/2017 07:44:00 AM               0  04/24/2017 07:44:15 AM
281107  05/25/2017 04:28:00 PM        90323827  05/25/2017 04:34:36 PM
281108  05/25/2017 04:30:00 PM               0  05/25/2017 04:30:07 PM
281109  05/25/2017 04:37:00 PM               0  05/25/2017 04:37:37 PM

       Breakdown_or_Running_Late School_Age_or_PreK
0                   Running Late         School-Age
1                   Running Late         School-Age
2                   Running Late              Pre-K
3                   Running Late         School-Age
4                   Running Late         School-Age
...                          ...                ...
281105              Running Late              Pre-K
281106              Running Late              Pre-K
281107              Running Late         School-Age
281108                 Breakdown         School-Age
281109              Running Late         School-Age

[281110 rows x 21 columns]

In [ ]:
# Then check for nulls in the column
# ---
#
df_clean.isnull().all(axis=0)

School_Year                        False
Bus_Breakdown_ID                   False
Run_Type                           False
Bus_Number                         False
Route_Number                       False
Reason                             False
Schools_Serviced                   False
Occurred_On                        False
Created_On                         False
Borough                            False
Bus_Company_Name                   False
How_Long_Delayed                   False
Number_Of_Students_On_The_Bus      False
Has_Contractor_Notified_Schools    False
Has_Contractor_Notified_Parents    False
Have_You_Alerted_OPT               False
Informed_On                        False
Incident_Number                    False
Last_Updated_On                    False
Breakdown_or_Running_Late          False
School_Age_or_PreK                 False
dtype: bool

In [ ]:
# Rename Boro column to Borough
# ---
#
#data.rename(columns={'Busbreakdown_ID': 'Bus_Breakdown_ID', 'Bus_No': 'Bus_Number', 'Boro': 'Borough'}, inplace=True)
#or
df_clean.columns=['School_Year', 'Bus_Breakdown_ID', 'Run_Type', 'Bus_Number', 'Route_Number',
       'Reason', 'Schools_Serviced', 'Occurred_On', 'Created_On', 'Borough',
       'Bus_Company_Name', 'How_Long_Delayed', 'Number_Of_Students_On_The_Bus',
       'Has_Contractor_Notified_Schools', 'Has_Contractor_Notified_Parents',
       'Have_You_Alerted_OPT', 'Informed_On', 'Incident_Number',
       'Last_Updated_On', 'Breakdown_or_Running_Late', 'School_Age_or_PreK']


df_clean

,School_Year,Bus_Breakdown_ID,Run_Type,Bus_Number,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Borough,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,24,11,Yes,No,Yes,11/05/2015 08:12:00 AM,0,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20,2,Yes,Yes,No,11/05/2015 08:12:00 AM,0,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,0,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,24,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:08 AM,Running Late,School-Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281105,2016-2017,1338452,Pre-K/EI,9345,2,Heavy Traffic,C530,04/05/2017 08:00:00 AM,04/05/2017 08:10:00 AM,Bronx,...,15,7,Yes,Yes,No,04/05/2017 08:10:00 AM,0,04/05/2017 08:10:15 AM,Running Late,Pre-K
281106,2016-2017,1341521,Pre-K/EI,0001,5,Heavy Traffic,C579,04/24/2017 07:42:00 AM,04/24/2017 07:44:00 AM,Bronx,...,20,0,Yes,Yes,No,04/24/2017 07:44:00 AM,0,04/24/2017 07:44:15 AM,Running Late,Pre-K
281107,2016-2017,1353044,Special Ed PM Run,GC0112,X928,Heavy Traffic,09003,05/25/2017 04:22:00 PM,05/25/2017 04:28:00 PM,Bronx,...,20,0,Yes,Yes,Yes,05/25/2017 04:28:00 PM,90323827,05/25/2017 04:34:36 PM,Running Late,School-Age
281108,2016-2017,1353045,Special Ed PM Run,5525D,Q920,Won`t Start,24457,05/25/2017 04:27:00 PM,05/25/2017 04:30:00 PM,Queens,...,24,0,Yes,Yes,No,05/25/2017 04:30:00 PM,0,05/25/2017 04:30:07 PM,Breakdown,School-Age
281109,2016-2017,1353046,Project Read PM Run,2530,K617,Other,21436,05/25/2017 04:36:00 PM,05/25/2017 04:37:00 PM,Brooklyn,...,45,7,Yes,Yes,Yes,05/25/2017 04:37:00 PM,0,05/25/2017 04:37:37 PM,Running Late,School-Age

In [ ]:
# Lastly we convert all values in our colums to lower case
# for ease of reading
# ---
#

df_clean.columns=df_clean.columns.str.lower()
df_clean.columns

Index(['school_year', 'bus_breakdown_id', 'run_type', 'bus_number',
       'route_number', 'reason', 'schools_serviced', 'occurred_on',
       'created_on', 'borough', 'bus_company_name', 'how_long_delayed',
       'number_of_students_on_the_bus', 'has_contractor_notified_schools',
       'has_contractor_notified_parents', 'have_you_alerted_opt',
       'informed_on', 'incident_number', 'last_updated_on',
       'breakdown_or_running_late', 'school_age_or_prek'],
      dtype='object')

In [ ]:
# Check the first 5 record the cleaned dataset
# ---
#
df_clean.head()

,school_year,bus_breakdown_id,run_type,bus_number,route_number,reason,schools_serviced,occurred_on,created_on,borough,...,how_long_delayed,number_of_students_on_the_bus,has_contractor_notified_schools,has_contractor_notified_parents,have_you_alerted_opt,informed_on,incident_number,last_updated_on,breakdown_or_running_late,school_age_or_prek
0,2015-2016,1227538,Special Ed AM Run,2621,J711,Heavy Traffic,75003,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,New Jersey,...,24,11,Yes,No,Yes,11/05/2015 08:12:00 AM,0,11/05/2015 08:12:14 AM,Running Late,School-Age
1,2015-2016,1227539,Special Ed AM Run,1260,M351,Heavy Traffic,06716,11/05/2015 08:10:00 AM,11/05/2015 08:12:00 AM,Manhattan,...,20,2,Yes,Yes,No,11/05/2015 08:12:00 AM,0,11/05/2015 08:13:34 AM,Running Late,School-Age
2,2015-2016,1227540,Pre-K/EI,418,3,Heavy Traffic,C445,11/05/2015 08:09:00 AM,11/05/2015 08:13:00 AM,Bronx,...,15,8,Yes,Yes,Yes,11/05/2015 08:13:00 AM,0,11/05/2015 08:13:22 AM,Running Late,Pre-K
3,2015-2016,1227541,Special Ed AM Run,4522,M271,Heavy Traffic,02699,11/05/2015 08:12:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,15,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:04 AM,Running Late,School-Age
4,2015-2016,1227542,Special Ed AM Run,3124,M373,Heavy Traffic,02116,11/05/2015 08:13:00 AM,11/05/2015 08:14:00 AM,Manhattan,...,24,6,No,No,No,11/05/2015 08:14:00 AM,0,11/05/2015 08:14:08 AM,Running Late,School-Age


## 5. Solution Implementation

Here we investigate the questions that would help craft our recommendations.

### 5.a) Questions

In [ ]:
# 1. Which bus companies that had the highest breakdowns?
# ---
#
breakdowns = df_clean.groupby(['bus_company_name']).count()

# Sort to get bus company with highest breakdowns
# ---
# YOUR CODE GOES BELOW
#

breakdowns['breakdown_or_running_late']

breakdowns = breakdowns.sort_values(by='breakdown_or_running_late', ascending=False)
print(breakdowns['breakdown_or_running_late'])
print()
print('The bus companies with highest break down: ,G.V.C., LTD., LEESEL TRANSPORTATION CORP (B2192) ')

### Let us correct this compagny name RELIANT TRANS, INC. (B232  to RELIANT TRANS, INC. (B232)

df_clean['bus_company_name']=df_clean['bus_company_name'].replace('RELIANT TRANS, INC. (B232', 'RELIANT TRANS, INC. (B232)')

## check the spelling
print()
print(df_clean['bus_company_name'].unique)

bus_company_name
G.V.C., LTD.                          19394
LEESEL TRANSPORTATION CORP (B2192)    17200
RELIANT TRANS, INC. (B232)            13741
PIONEER TRANSPORTATION CO             12017
BORO TRANSIT, INC.                    11953
                                      ...
SMART PICK INC                            1
R & C TRANSIT, INC. (B2321)               1
L&M Bus Corp.                             1
FORTUNA BUS COMPANY                       1
phillip bus service                       1
Name: breakdown_or_running_late, Length: 117, dtype: int64

The bus companies with highest break down: ,G.V.C., LTD., LEESEL TRANSPORTATION CORP (B2192)

<bound method Series.unique of 0         RELIANT TRANS, INC. (B232)
1          HOYT TRANSPORTATION CORP.
2                       G.V.C., LTD.
3         RELIANT TRANS, INC. (B232)
4         RELIANT TRANS, INC. (B232)
                     ...
281105                  G.V.C., LTD.
281106                  G.V.C., LTD.
281107           G.V.C. LTD. (B2192)
281108     LITTLE RICHIE BUS SERVICE
281109    RELIANT TRANS, INC. (B232)
Name: bus_company_name, Length: 281110, dtype: object>

In [ ]:
# 2. What were the top 3 reasons for bus delays?
# ---
#
bus_delay = df_clean.groupby(['reason']).count()[['how_long_delayed']].reset_index()

# Sort to get the most frequent reason
# ---
# YOUR CODE GOES BELOW
#

bus_delay=bus_delay.sort_values(by='how_long_delayed', ascending=False)
print(bus_delay)
print()

print('Top 3 reasons for bus delays: Heavy Traffic, Other, Mechanical Problem')

                        reason  how_long_delayed
3                Heavy Traffic            173221
6                        Other             37579
5           Mechanical Problem             28162
9                  Won`t Start             12283
2                    Flat Tire              8411
8           Weather Conditions              6932
4  Late return from Field Trip              5704
7                  Problem Run              4068
0                     Accident              2526
1            Delayed by School              2222

Top 3 reasons for bus delays: Heavy Traffic, Other, Mechanical Problem

In [ ]:
# 3. How many students were in the buses when they broke down?
# ---
#
numberStudent=df_clean.groupby(['number_of_students_on_the_bus']).count()[['bus_breakdown_id']].reset_index()

#print(df_clean['bus_breakdown_id'].unique())

#how many rows  there are for each breakdown or running late category
numberStudent1=df_clean.groupby(['breakdown_or_running_late'])['number_of_students_on_the_bus'].count()

print('Count of rows for each delayed type:' ,numberStudent1)

print()


students_in_buses = df_clean[df_clean['breakdown_or_running_late'] == 'Breakdown'].groupby('breakdown_or_running_late')['number_of_students_on_the_bus'].sum().reset_index()
print(df_clean['breakdown_or_running_late'].unique())
print('Sudents in the bus when breakdown:', students_in_buses)

# student in the bus when rumming late

students_in_buses = df_clean[df_clean['breakdown_or_running_late'] == 'Running Late'].groupby('breakdown_or_running_late')['number_of_students_on_the_bus'].sum().reset_index()
print(df_clean['breakdown_or_running_late'].unique())
print('Sudents in the bus when Running Late:', students_in_buses)




#df_clean[['breakdown_or_running_late','number_of_students_on_the_bus']].sample(10)

Count of rows for each delayed type: breakdown_or_running_late
Breakdown        31057
Running Late    250053
Name: number_of_students_on_the_bus, dtype: int64

['Running Late' 'Breakdown']
Sudents in the bus when breakdown:   breakdown_or_running_late  number_of_students_on_the_bus
0                 Breakdown                          58329
['Running Late' 'Breakdown']
Sudents in the bus when Running Late:   breakdown_or_running_late  number_of_students_on_the_bus
0              Running Late                         890829

In [ ]:
# 4. Which were most frequent reasons for bus breakdowns?
# ---
#


#breakdown_reasons = df_clean[df_clean.breakdown_or_running_late == 'breakdown'].groupby(['reason']).count()

df_clean['breakdown_or_running_late']=='Breakdown'



true_count = (df_clean['breakdown_or_running_late'] == 'Breakdown').sum()

#size() fct counts the number of rows in each group (for each unique reason).
reason= df_clean[df_clean['breakdown_or_running_late'] == 'Breakdown'].groupby(['reason']).size()



print(true_count, df_clean.shape,reason )
# Sort to get most frequent reasons
# ---
# YOUR CODE GOES BELOW
#
sorted_reason = reason.sort_values(ascending=False)
print(sorted_reason)

print('The most frequent reasons for for bus breakdowns are: Mechanical Problem, Won`t Start')

31057 (281110, 21) reason
Accident                         202
Delayed by School                  7
Flat Tire                       4038
Heavy Traffic                    419
Late return from Field Trip       35
Mechanical Problem             14985
Other                           3530
Problem Run                       28
Weather Conditions                82
Won`t Start                     7731
dtype: int64
reason
Mechanical Problem             14985
Won`t Start                     7731
Flat Tire                       4038
Other                           3530
Heavy Traffic                    419
Accident                         202
Weather Conditions                82
Late return from Field Trip       35
Problem Run                       28
Delayed by School                  7
dtype: int64
The most frequent reasons for for bus breakdowns are: Mechanical Problem, Won`t Start

In [ ]:
# 5. What were the most frequent reasons for the bus running late?
# ---
#
reasons = df_clean.groupby(['reason','how_long_delayed']).count()
#rea=df_clean.groupby(['reason','breakdown_or_running_late']).count()


# Get the records with running late reasons and sort to get most frequent reasons
# ---
# YOUR CODE GOES BELOW
#

rea = df_clean[df_clean['breakdown_or_running_late'] == 'Running Late'].groupby(['reason', 'breakdown_or_running_late']).count()
reasort=rea.sort_values(by=rea.columns[1], ascending=False)
#print(reasort)

print('The most frequent reasons for the bus running late: ', reasort.head(3))

The most frequent reasons for the bus running late:                                                school_year  bus_breakdown_id  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                    172802            172802
Other              Running Late                     34049             34049
Mechanical Problem Running Late                     13177             13177

                                              run_type  bus_number  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                 172801      172798
Other              Running Late                  34049       34046
Mechanical Problem Running Late                  13177       13177

                                              route_number  schools_serviced  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                     172799            172799
Other              Running Late                      34047             34047
Mechanical Problem Running Late                      13177             13177

                                              occurred_on  created_on  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                    172802      172802
Other              Running Late                     34049       34049
Mechanical Problem Running Late                     13177       13177

                                              borough  bus_company_name  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                163209            172802
Other              Running Late                 33059             34049
Mechanical Problem Running Late                 12529             13177

                                              how_long_delayed  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                         172802
Other              Running Late                          34049
Mechanical Problem Running Late                          13177

                                              number_of_students_on_the_bus  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                                      172802
Other              Running Late                                       34049
Mechanical Problem Running Late                                       13177

                                              has_contractor_notified_schools  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                                        172802
Other              Running Late                                         34049
Mechanical Problem Running Late                                         13177

                                              has_contractor_notified_parents  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                                        172802
Other              Running Late                                         34049
Mechanical Problem Running Late                                         13177

                                              have_you_alerted_opt  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                             172802
Other              Running Late                              34049
Mechanical Problem Running Late                              13177

                                              informed_on  incident_number  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                    172802           172802
Other              Running Late                     34049            34049
Mechanical Problem Running Late                     13177            13177

                                              last_updated_on  \
reason             breakdown_or_running_late
Heavy Traffic      Running Late                        172802
Other              Running Late                         34049
Mechanical Problem Running Late                         13177

                                              school_age_or_prek
reason             breakdown_or_running_late
Heavy Traffic      Running Late                           172802
Other              Running Late                            34049
Mechanical Problem Running Late                            13177

In [ ]:
# 6. What was the average delay time for each reason type?
# ---
#
#avg_delay = df_clean.groupby('reason').mean().reset_index()

avg_delay = df_clean[['reason', 'how_long_delayed']].groupby('reason').mean(numeric_only=True).reset_index()


# Get the records with reasons and how long on average a delay took then sort
# ---
# YOUR CODE GOES BELOW
#


sorted_avg_delay = avg_delay.sort_values(by='how_long_delayed', ascending=True)


print(sorted_avg_delay[['reason', 'how_long_delayed']])

#a = df_clean[df_clean['reason'] == 'Late return from Field Trip']
#a_grouped = a['how_long_delayed'].mean()
#print(a_grouped)

                        reason  how_long_delayed
1            Delayed by School         21.701620
9                  Won`t Start         27.398355
3                Heavy Traffic         27.749101
2                    Flat Tire         27.767328
6                        Other         29.012906
5           Mechanical Problem         29.110077
8           Weather Conditions         30.192008
7                  Problem Run         31.496313
0                     Accident         34.659541
4  Late return from Field Trip         62.970898

### 5.b) Recommendations

From the above analysis, below are our recommendations:

1.   
2.

## 6. Challenging your Solution

During this step, we review our solution and implement  approaches that could potentially provide a better outcome. In our case, we could propose the following question that wasn't answered in our solution because it couldn't have greatly contributed to our recommendation.

In [ ]:
# Which boroughs experienced the most breakdowns?
# ---
#
print(df_clean['borough'].unique())
nan_count = df_clean['borough'].isna().sum()

print('nan count',nan_count)
breakdowns = df_clean[df_clean['breakdown_or_running_late'] == 'Breakdown']
breakdowns1 = breakdowns.groupby(['borough']).count()

# Sort to get bus company with highest breakdowns
# ---
# YOUR CODE GOES BELOW



breakdowns_sorted = breakdowns1.sort_values(by='breakdown_or_running_late', ascending=False)

# Display the sorted result
print('Total boroughs breakdowns', breakdowns_sorted[['breakdown_or_running_late']].sum())

print(breakdowns_sorted['breakdown_or_running_late'])
print('Which boroughs experienced the most breakdowns?', breakdowns_sorted['breakdown_or_running_late'].head(3))



###############Running late



Late = df_clean[df_clean['breakdown_or_running_late'] == 'Running Late']
Late1 = Late.groupby(['borough']).count()

# Sort to get bus company with highest breakdowns
# ---
# YOUR CODE GOES BELOW



Late_sorted = Late1.sort_values(by='breakdown_or_running_late', ascending=False)
print()
print()
# Display the sorted result
print('Total boroughs Running Late', Late_sorted[['breakdown_or_running_late']].sum())

print(Late_sorted['breakdown_or_running_late'])

['New Jersey' 'Manhattan' 'Bronx' 'Westchester' 'Brooklyn'
 'Rockland County' 'Nassau County' nan 'Queens' 'Staten Island'
 'Connecticut' 'All Boroughs']
nan count 13461
Total boroughs breakdowns breakdown_or_running_late    30006
dtype: int64
borough
Bronx              9287
Queens             9118
Brooklyn           6826
Manhattan          3359
Nassau County       685
Staten Island       454
Westchester         139
New Jersey           66
Rockland County      42
All Boroughs         20
Connecticut          10
Name: breakdown_or_running_late, dtype: int64
Which boroughs experienced the most breakdowns? borough
Bronx       9287
Queens      9118
Brooklyn    6826
Name: breakdown_or_running_late, dtype: int64


Total boroughs Running Late breakdown_or_running_late    237643
dtype: int64
borough
Manhattan          64818
Bronx              61665
Brooklyn           55413
Queens             28942
Staten Island      13453
Westchester         6954
Nassau County       3439
New Jersey          1517
Rockland County      833
All Boroughs         409
Connecticut          200
Name: breakdown_or_running_late, dtype: int64

Our observations:

1.   
2.  


How does this observation tie to our solution?

## 7. Follow up questions

During this step, you rethink and propose other ways that you can improve your solution.

### a). Did we have the right data?

### b). Do we need other data to answer our question?

You can look into the questions you brainstormed that you weren't taken into account during analysis due to a lack of data. Were those questions important to have been left out  of your analysis?

### c). Did we have the right question?

Were there any other questions that we needed to have answered?